### ISSUE TITLE
Error while building Quantica MakeFile FIX attached !

### ISSUE THREAD

**Issue by KrisToday** [yorickdewid/Quantica#18]
Hi Quantica db gives an error while building,

/usr/bin/ld: src/webapi.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line

to fix this add 

-lpthread at LDFLAGS in the makefile 

Cheers,

**Comment by yorickdewid** [comment]
On what platform does this happen? On most Linux distro's the linker adds pthread automatically when threading symbols are used

**Comment by KrisToday** [comment]
The bug was found in arch-linux testing :)
