### ISSUE TITLE
Are you using Stack to parse sql like query structure ?

### ISSUE THREAD

**Issue by flouthoc** [yorickdewid/Quantica#39]

**Comment by yorickdewid** [comment]
I'm not sure which Stack you're referring to, but the SQL parser is build in pure C. It does uses a stack datastructure though.

**Comment by flouthoc** [comment]
Oops got it , it was a vague question :grin:

**Comment by yorickdewid** [comment]
No problem. If you'd like to know more about internals I can setup a gitter channel.

**Comment by flouthoc** [comment]
yes , it would be great , or some irc qroup , what's your irc nick ?

**Comment by yorickdewid** [comment]
Look for `Dinux` on Freenode.Whats your timezone?
